[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["model"]
namespaces = false

[project]
name = "foundation-workspace"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = []
