# Default training configuration placeholder.
optimizer:
  name: adamw
  lr: 0.0002
  weight_decay: 0.01
scheduler:
  name: cosine
  warmup_ratio: 0.03
fsdp:
  enabled: false
  sharding_strategy: full_shard
deepspeed:
  enabled: false
  config: null
