model_cfg: configs/models/fm-toy.json
data_catalog: data/catalog.toy.yaml
mixture: toy_mix
precision: fp32
optimizer:
  name: adamw
  betas: [0.9, 0.95]
  weight_decay: 0.01
  lr: 5.0e-4
  warmup_steps: 50
  schedule: constant
distributed:
  backend: gloo
  ddp: false
  fsdp: false
  fsdp_policy: full_shard
  grad_accum_steps: 1
  gradient_clip: 1.0
logging:
  wandb: false
  tensorboard: false
  modal_ledger_interval: 10
  log_every: 10
losses:
  lambda_geo: 0.0
  modal:
    apply_on: ["planner"]
    lambda_mod: 0.0
    lambda_planner: 1.0
    lambda_token: 0.0
    tau_planner: 1.0
    tau_token: 1.0
    slot_len: 128
    view_window: 1
    slot_weights: [1.0, 0.5]
    stop_grad_projection: true
    eps: 1.0e-6
    clip_kl: 10.0
    token_topk: 64
ledger:
  lambda_mod: 0.0
  apply_on: []
  span_tokens: []
  view:
    slot_len: 128
    window: 1
gate:
  armijo_alpha: 1.0e-4
  trust_radius_init: 0.05
  kl_smooth_max: 0.5
  stability_slice_ratio: 0.25
  backtrack_factor: 0.5
  widen_view_on_reject: false
  max_view_window: 2
checkpoints:
  output_dir: ckpts/toy
  save_every_steps: 50
  save_every_tokens: 100000
  keep_last: 2
  resume: never
engine:
  enabled: false
  eval_interval: 200
  batch_size: 2
  qfc_tolerance: 1.0e-8
