model_cfg: configs/models/fm-toy.json
data_catalog: data/catalog.toy.yaml
mixture: toy_mix
precision: fp32
optimizer:
  name: adamw
  betas: [0.9, 0.95]
  weight_decay: 0.01
  lr: 5.0e-4
  warmup_steps: 50
  schedule: constant
distributed:
  backend: gloo
  fsdp: false
  fsdp_policy: full_shard
  grad_accum_steps: 1
logging:
  wandb: false
  tensorboard: false
  modal_ledger_interval: 10
ledger:
  lambda_mod: 0.0
  apply_on: []
  span_tokens: []
  view:
    slot_len: 128
    window: 1
gate:
  armijo_alpha: 1.0e-4
  trust_radius_init: 0.05
  kl_smooth_max: 0.5
