name: Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build training image
        run: docker build -f Dockerfile --target training -t foundation/training:ci .

  build-serving:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build serving image
        run: docker build -f Dockerfile --target serving -t foundation/serving:ci .
