name: Python

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install workspace
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./model
          python -m pip install ruff
      - name: Ruff Lint
        run: python -m ruff check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install workspace
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./model
          python -m pip install -r requirements-dev.txt
      - name: Pytest
        run: pytest -q
      - name: Evaluate
        if: github.event_name == 'pull_request'
        run: python -m fm_eval.runner --config configs/eval/kill_numbers.yaml

  build-wheels:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install maturin
          maturin build -m model/fm_bindings/Cargo.toml
