name: Rust

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo Clippy
        run: |
          cargo clippy --all-targets --all-features --workspace -D warnings

  test:
    runs-on: ubuntu-latest
    needs: clippy
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo Test Engine
        run: cargo test -p engine
      - name: Cargo Test Serving
        run: cargo test --manifest-path serving/rust/Cargo.toml
